### ISSUE TITLE
ViewModel architectural issues

### ISSUE THREAD

**Issue by bhm** [Jakebreen/pokecart#9]
https://github.com/Jakebreen/pokecart/blob/bfab8c95cd7f5d5141edfd4796736809d87d896a/app/src/main/java/uk/co/jakebreen/pokecart/ui/cart/CartItemViewModel.kt#L11

1. All VMs know about view binding. That's backwards AFAIU MVVM. I'm seeing this trend lately and I believe it breaks the concept of a VM that differentiates a VM from a Presenter in MVP (or Controller in MVC). VM should have no view reference. And this companion object technically creates no view reference, but it knows of view logic. No view reference seems to me like a core reason behind not pushing view logic into the VM class. Correct me if I'm wrong, but binding data belongs to View or a Binder impl in MVVM.

2. `CartItemViewModel` is not really a VM. It exposes no objects to observe/bind to. It's a DTO style class, which technically I think it makes it a domain object. I'd fix it by turning it into a plain `data class CartItem` and make it immutable at the same time: `var > val`

3. If `CartItemViewModel` is indeed meant to be a VM, there is an inverted dependency in `CartRepository` via the `CartItemViewModel::from`. Thus your dependency graph lies. Given you follow advice in #2, this would be fixed too.

4. I suggest removing the factory method `from` and just add a constructor that does the same job, sans passing `Resource` class. Extract Uri at repository level and pass the Uri to constructor.

5. `CartRepository` has two further problems. One being the `val cartPokemon` is a `MutableLiveData<MutableMap<>>`. Given I have a reference, I can mutate contents outside of the `CartRepository`. Refactoring constructor to accept a `private val Map<>` and copy it into a non-constructor property will lend to immutability.

6. `CartRepository` uses LiveData. This is may be problematic as you are pulling a VM level class to handle what amounts to Observer pattern. Not ideal, but I would let it slide in a pinch as observer java API is not the most ideal.

**Comment by Jakebreen** [comment]
This is great advice, I will implement it in the coming days and let you know how it goes, thank you!

**Comment by Jakebreen** [comment]
I made a commit a few weeks ago to rectify the issues you raised, it was all solid advice so thank you.
https://github.com/Jakebreen/pokecart/commit/055c5e2f76de990490cd6758c1e9add665b099af#diff-80c593fe8a7e357fe262b040ce439893d18b1b84e498b763a9fa9a5bdc5034ba

I needed to introduce another class to retain the mutability of the CartRepository, InMemoryCartRepository though this does not expose any mutable data and can only be manipulated from the calling methods. This could also have been achieved with a database...
